"""Add login_activity table and super_admin role

Revision ID: 5142dc460a7a
Revises: rename_email_005
Create Date: 2026-03-12 15:45:40.907447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5142dc460a7a'
down_revision: Union[str, Sequence[str], None] = 'rename_email_005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slots_id'), table_name='slots')
    op.drop_table('slots')
    op.drop_index(op.f('ix_blocked_dates_date'), table_name='blocked_dates')
    op.drop_index(op.f('ix_blocked_dates_id'), table_name='blocked_dates')
    op.drop_table('blocked_dates')
    # Update Enum 'role' in users table
    op.execute("ALTER TABLE users MODIFY COLUMN role ENUM('user', 'admin', 'super_admin') DEFAULT 'user'")

    # Create login_activity table
    op.create_table('login_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_activity_id'), 'login_activity', ['id'], unique=False)

    op.alter_column('bookings', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_cancelled_by_user'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['cancelled_by'], ['id'])
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_cancelled_by_user'), 'bookings', 'users', ['cancelled_by'], ['id'], ondelete='SET NULL')
    op.alter_column('bookings', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
               
    op.drop_index(op.f('ix_login_activity_id'), table_name='login_activity')
    op.drop_table('login_activity')
    
    op.execute("ALTER TABLE users MODIFY COLUMN role ENUM('user', 'admin') DEFAULT 'user'")
    op.create_table('blocked_dates',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('reason', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('blocked_dates_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_blocked_dates_id'), 'blocked_dates', ['id'], unique=False)
    op.create_index(op.f('ix_blocked_dates_date'), 'blocked_dates', ['date'], unique=True)
    op.create_table('slots',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('start_time', mysql.TIME(), nullable=False),
    sa.Column('end_time', mysql.TIME(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_slots_id'), 'slots', ['id'], unique=False)
    # ### end Alembic commands ###
